name: CI

on: [push]

jobs:
  test:
    name: Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # https://github.com/bahmutov/npm-install
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm test
